"""Calibrate 3DThesis beam depth and efficiency against measured melt pools."""

from __future__ import annotations

import argparse
import itertools
import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent

LITERATURE_EFFICIENCY = 0.40
VALIDITY_PEAK_C = 6000.0
VALIDITY_PEAK_K = VALIDITY_PEAK_C + 273.15

BEAM_TEMPLATE = """# Generated by calibrate_beam.py: calibration grid point {index}
# Depth_Z = {depth_z:.4g} m ({depth_z_um:.1f} um)
# Efficiency = {efficiency:.4g}
# Width_X/Y is fixed by the 100 um D4sigma spot under the 3DThesis
# convention: input width = sqrt(6)*sigma = 0.6124*D4sigma.
Shape
{{
    Width_X {width:.6g}
    Width_Y {width:.6g}
    Depth_Z {depth_z:.6g}
}}

Intensity
{{
    Power {power:g}
    Efficiency {efficiency:.6g}
}}
"""


def write_single_track_path(path: Path, speed_m_s: float,
                            length_mm: float = 1.4, start_mm: float = -0.2) -> None:
    end_mm = start_mm + length_mm
    path.write_text(
        "Mode X(mm) Y(mm) Z(mm) Pmod Vel(m/s)/Time(s)\n"
        f"1 {start_mm:.9f} 0.000000000 0.000000000 0 1.000000000e-07\n"
        f"0 {end_mm:.9f} 0.000000000 0.000000000 1 {speed_m_s:.9f}\n",
        encoding="utf-8",
    )


def read_pool(case_dir: Path, z_res_m: float,
              liquidus_k: float = 1708.0) -> dict:
    candidates = sorted((case_dir / "Data").glob("*.Solidification.Final*.csv"))
    if not candidates:
        raise FileNotFoundError(f"No Solidification.Final file under {case_dir}/Data")
    frame = pd.read_csv(candidates[-1])
    melted = frame[frame["numMelt"] > 0] if "numMelt" in frame else frame
    if not len(melted):
        return {"depth_um": np.nan, "width_um": np.nan, "peak_k": np.nan,
                "melted_points": 0}

    depth = float(melted["depth"].max()) if "depth" in melted else np.nan
    if not np.isfinite(depth):
        depth = float(-melted["z"].min())

    if "MP_width" in melted and np.isfinite(melted["MP_width"]).any():
        width = float(melted["MP_width"].max())
    else:
        top = melted[np.isclose(melted["z"], 0.0, atol=0.51 * z_res_m)]
        width = float(np.ptp(top["y"])) if len(top) else np.nan

    # Solidification T is the temperature at solidification, not the thermal
    # history peak. Only a snapshot temperature field can supply a valid peak.
    peak = np.nan
    if "T" in frame.columns:
        observed = float(pd.to_numeric(frame["T"], errors="coerce").max())
        # Reject liquidus-clamped solidification temperatures.
        if observed > 1.05 * liquidus_k:
            peak = observed

    return {
        "depth_um": depth * 1e6,
        "width_um": width * 1e6,
        "peak_k": peak,
        "melted_points": int(len(melted)),
    }


def run_case(case_dir: Path, thesis_bin: Path, dry_run: bool) -> None:
    print(f"      $ {thesis_bin} ParamInput.txt   (cwd={case_dir.name})")
    if dry_run:
        return
    started = time.time()
    result = subprocess.run([str(thesis_bin), "ParamInput.txt"],
                            cwd=case_dir, text=True, capture_output=True)
    if result.returncode != 0:
        sys.stderr.write(result.stderr[-3000:])
        raise SystemExit(f"3DThesis failed: {case_dir}")
    print(f"        elapsed {time.time() - started:.1f} s")


def load_targets(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path, comment="#")
    frame["has_data"] = frame[["width_um", "depth_um"]].notna().all(axis=1)
    return frame


def z_resolution(case_dir: Path) -> float:
    text = (case_dir / "Domain.txt").read_text(encoding="utf-8")
    block = re.search(r"Z\s*\{[^}]*Res\s+([0-9.eE+-]+)", text, re.S)
    return float(block.group(1)) if block else 2.5e-6


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--thesis-bin", type=Path, default=None)
    parser.add_argument("--targets", type=Path, default=HERE / "calib_targets.csv")
    parser.add_argument("--workdir", type=Path, default=HERE / "calib_runs")
    parser.add_argument("--output", type=Path, default=HERE / "calibration_result")
    parser.add_argument("--depth-z-um", default="20,25,30,35,40,50,60",
                        help="Comma-separated Depth_Z grid in µm.")
    parser.add_argument("--efficiency", default="0.30,0.35,0.40,0.45",
                        help="Comma-separated Efficiency grid; 0.40 is a literature anchor.")
    parser.add_argument("--width-m", type=float, default=6.124e-5,
                        help="Width_X/Y fixed by the 100 µm D4sigma spot; not fitted.")
    parser.add_argument("--depth-weight", type=float, default=2.0,
                        help="Melt-depth weight in the objective; default 2.")
    parser.add_argument("--liquidus-k", type=float, default=1708.0,
                        help="Liquidus used to reject non-peak Solidification T values.")
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--report-only", action="store_true")
    args = parser.parse_args()

    targets = load_targets(args.targets)
    usable = targets[targets["has_data"]]
    print("=" * 70)
    print(f"Calibration targets: {len(targets)} conditions; {len(usable)} have measurements")
    print("=" * 70)
    if not len(usable):
        print(f"\n{args.targets.name} contains no measured values.")
        print("Digitize bare-plate width and depth from Figure 5 of Micromachines")
        print("2024 15(2) 170, fill width_um/depth_um, and rerun this script.")
        print("\nLiterature constraints available before fitting:")
        print(f"  - Center Efficiency near {LITERATURE_EFFICIENCY}"
              " (doi:10.1007/s40192-024-00382-2).")
        print(f"  - Above {VALIDITY_PEAK_C:.0f} °C, the conduction model increasingly"
              " under-predicts melt depth.")
        return 1

    depth_grid = [float(v) * 1e-6 for v in args.depth_z_um.split(",")]
    efficiency_grid = [float(v) for v in args.efficiency.split(",")]
    combos = list(itertools.product(depth_grid, efficiency_grid))
    total = len(combos) * len(usable)
    print(f"Grid: {len(depth_grid)} × {len(efficiency_grid)} = {len(combos)} parameter sets")
    print(f"Each set runs {len(usable)} conditions -> {total} total 3DThesis runs\n")

    if not args.report_only and not args.dry_run and args.thesis_bin is None:
        raise SystemExit("--thesis-bin is required unless --dry-run is used")

    args.workdir.mkdir(parents=True, exist_ok=True)
    args.output.mkdir(parents=True, exist_ok=True)
    z_res = z_resolution(HERE)

    records = []
    for index, (depth_z, efficiency) in enumerate(combos):
        tag = f"dz{depth_z * 1e6:g}_eff{efficiency:g}"
        print(f"[{index + 1}/{len(combos)}] Depth_Z={depth_z * 1e6:g} µm  "
              f"Efficiency={efficiency:g}")
        for _, target in usable.iterrows():
            case = args.workdir / f"{tag}__{target['label']}"
            case.mkdir(parents=True, exist_ok=True)
            (case / "Data").mkdir(exist_ok=True)
            for name in ("Material.txt", "Domain.txt", "Mode.txt",
                         "Output.txt", "Settings.txt", "ParamInput.txt"):
                shutil.copy2(HERE / name, case / name)
            (case / "Beam.txt").write_text(
                BEAM_TEMPLATE.format(
                    index=index + 1, depth_z=depth_z, depth_z_um=depth_z * 1e6,
                    efficiency=efficiency, width=args.width_m,
                    power=target["power_w"],
                ), encoding="utf-8",
            )
            write_single_track_path(case / "Path.txt", float(target["speed_m_s"]))

            done = any((case / "Data").glob("*.Solidification.Final*.csv"))
            if not (args.resume and done) and not args.report_only:
                run_case(case, args.thesis_bin, args.dry_run)

            if args.dry_run:
                continue
            try:
                pool = read_pool(case, z_res, args.liquidus_k)
            except FileNotFoundError:
                continue
            records.append({
                "depth_z_um": depth_z * 1e6, "efficiency": efficiency,
                "label": target["label"], "power_w": target["power_w"],
                "speed_m_s": target["speed_m_s"],
                "sim_width_um": pool["width_um"], "sim_depth_um": pool["depth_um"],
                "exp_width_um": target["width_um"], "exp_depth_um": target["depth_um"],
                "peak_k": pool["peak_k"],
                "beyond_validity": bool(np.isfinite(pool["peak_k"])
                                        and pool["peak_k"] > VALIDITY_PEAK_K),
            })

    if args.dry_run:
        print("\n[dry-run] Cases were generated without running 3DThesis; inspect Beam.txt.")
        return 0
    if not records:
        print("No results are available to summarize.")
        return 1

    frame = pd.DataFrame(records)
    frame["width_err"] = frame["sim_width_um"] / frame["exp_width_um"] - 1.0
    frame["depth_err"] = frame["sim_depth_um"] / frame["exp_depth_um"] - 1.0
    frame.to_csv(args.output / "calibration_runs.csv", index=False)

    grouped = frame.groupby(["depth_z_um", "efficiency"]).apply(
        lambda g: pd.Series({
            "rms_error": float(np.sqrt(
                (g["width_err"] ** 2).mean()
                + args.depth_weight * (g["depth_err"] ** 2).mean()
            ) / np.sqrt(1 + args.depth_weight)),
            "mean_width_err": float(g["width_err"].mean()),
            "mean_depth_err": float(g["depth_err"].mean()),
            "max_peak_k": float(g["peak_k"].max()),
            "any_beyond_validity": bool(g["beyond_validity"].any()),
        }), include_groups=False,
    ).reset_index().sort_values("rms_error")
    grouped.to_csv(args.output / "calibration_grid.csv", index=False)

    best = grouped.iloc[0]
    print("\n" + "=" * 70)
    print("Best fit")
    print("=" * 70)
    print(f"  Depth_Z    = {best['depth_z_um']:.4g} µm   "
          f"(current Beam.txt: 35 µm)")
    print(f"  Efficiency = {best['efficiency']:.4g}   (current 0.35, literature "
          f"{LITERATURE_EFFICIENCY})")
    print(f"  weighted RMS error {best['rms_error'] * 100:.1f}%  ·  "
          f"width bias {best['mean_width_err'] * 100:+.1f}%  ·  "
          f"depth bias {best['mean_depth_err'] * 100:+.1f}%")
    if not np.isfinite(best["max_peak_k"]):
        print("  Peak temperature unknown: Solidification T is an event temperature,")
        print("  not the thermal-history peak. Run a Snapshot case to test the 6000 °C limit.")
        print("\nTop five:")
        print(grouped.head(5).to_string(index=False))
        return 0
    print(f"  Maximum peak temperature {best['max_peak_k'] - 273.15:.0f} °C", end="")
    if best["any_beyond_validity"]:
        print(f"  WARNING: above the {VALIDITY_PEAK_C:.0f} °C validity threshold;"
              " the fit includes conduction-model extrapolation.")
    else:
        print(f"  within the {VALIDITY_PEAK_C:.0f} °C validity range")

    print("\nTop five:")
    print(grouped.head(5).to_string(index=False))
    print(f"\nWrote {args.output}/calibration_grid.csv and calibration_runs.csv")
    print("\nAfter review, copy the best values into Beam.txt and update provenance:")
    print("  Upgrade Depth_Z/Efficiency only to the grade justified by the measurements.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
